### ISSUE TITLE
Holbeck Riot

### ISSUE THREAD

**Issue by paganjones7** [timwaters/leeds_riot_map#1]
You missed out the Holbeck riot over the appoinment of a new vicar in the 18th century.Little known about but see my thread here:
http://secretleeds.com/viewtopic.php?t=4644

**Comment by timwaters** [comment]
Many thanks! https://ohiostatepress.org/books/Complete%20PDFs/Wiles%20Freshest/07.pdf appears to have good info

Will add it to Wikipedia list too

**Comment by paganjones7** [comment]
Thanks,I hadn't seen this ,interesting chapter.I used the online access to the newspaper library to read the actual accounts in the Leeds intelligencer which are fascinating.It went on for weeks and involved not just riots in the short extract but people breaking into the church and actually crapping in the aisles in one case!
It appears that they thought the vicar had been appointed as favour to the family who had the right to appoint vicars.The sermon he preached when he left is supposed to contain fulminations against the people of Holbeck but I can't find a free online copy as you have to have access via the university portals and I haven't found anyone interested enough to download and send a copy of it to me.

Steve Jones

-----Original Message-----

**Comment by timwaters** [comment]
Okay have added the riot, I've called it "Holbeck Chapel Riot" Many thanks!

The sermon looks interesting, it appears to be available to US libraries only online
